<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>

    <form action="/" method="get">
        <label for="userName">What is your name?</label>
        <input type="text" placeholder="name" id="userName">
        <input type="submit" id="nameSubmit">
    </form>
        <?php if(isset($name)) : ?>
        <h1><?= htmlspecialchars($name); ?>'s to do list</h1>
        <?php else: ?>
        <h1>to do list</h1>
        <?php endif; ?>

<!--        --><?php //if (isset($name)) : ?>
<!--            <h2>Hello --><?//= htmlspecialchars($name); ?><!--!</h2>-->
<!--        --><?php //else: ?>
<!--            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>-->
<!--        --><?php //endif; ?>

        <form action="/" method="post">
            <label for="addTodo">Add a to-do item</label>
            <input type="text" id="addTodo" name="addTodo">
            <input type="submit" id="todoSubmit">
        </form>

        <div id="displayTodo">
            <h2>To do items</h2>
            <?php if(isset($item)) : ?>
                <li><?= htmlspecialchars($item); ?></li>
            <?php else: ?>
                <p></p>
            <?php endif; ?>

        </div>
        <div id="doneTodo">
            <h2>Done items</h2>
        </div>

    <script>
        // document.querySelector("#nameSubmit").addEventListener("click", function(event) {
        //     event.preventDefault();
        // }, false);
        // document.querySelector("#todoSubmit").addEventListener("click", function(event) {
        //     event.preventDefault();
        // }, false);
    </script>
    </body>
</html>
