<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 42px;
                font-weight: 200;
                margin-bottom: 0;
            }

            .doneItem input {
                display: none;
            }

            .none {
                display: none;
            }

            .doneItem {
                display: list-item;
            }
        </style>
    </head>
    <body>

    <form action="/" method="get" id="userNameForm">
        <label for="userName">What is your name?</label>
        <input type="text" placeholder="name">
        <input type="submit" id="nameSubmit">
    </form>
    <h1 id="username"></h1><h1>To do list</h1>

        <form action="/addItem" method="post">
            <label for="addTodo">Add a to-do item</label>
            <input type="text" id="addTodo" name="addTodo">
            <input type="submit" id="todoSubmit">
        </form>

        <div id="todoItem">
            <h2>To do items</h2>
            <?php
            if(isset($items)) :
                foreach($items as $item) {
                    echo '<li>' . $item["item"] . '<input type="checkbox" value="' . $item["id"] . '" class="itemCheck"></li><br>';
                    }
            ?>
            <?php else: ?>
                <p></p>
            <?php endif; ?>

        </div>
        <div>
            <h2>Done items</h2>
            <div id="doneItemList">
                <?php
                if(isset($doneItems)) :
                    foreach($doneItems as $doneitem) {
                        echo '<li>' . $doneitem["item"] . '</li><br>';
                    }
                    ?>
                <?php else: ?>
                    <p></p>
                <?php endif; ?>
            </div>
        </div>

    <script>
        const nameField = document.getElementById("username");
        const userNameForm = document.getElementById("userNameForm");
        let itemCheckBtnList = document.querySelectorAll(".itemCheck");
        const doneItemField = document.getElementById("doneItemList");
        const toDoItemField = document.getElementById("todoItem");

        (function(){
            for(let i = 0; i < itemCheckBtnList.length; i ++) {
                itemCheckBtnList[i].addEventListener("change", function(e) {
                    let url = '/moveItem'

                    fetch(url, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({taskId : this.value})
                    })
                        .then(response => response.json())
                        .then((obj)=> {
                            // move item here.
                            this.parentElement.classList.add('none');
                            doneItemField.innerHTML +=  "<li class='doneItem'>" + this.parentElement.innerHTML + "</li>";
                            console.log(obj);
                        });
                })
            }

        })()
    </script>
    </body>
</html>
