<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>

    <form action="/" method="get" id="userNameForm">
        <label for="userName">What is your name?</label>
        <input type="text" placeholder="name">
        <input type="submit" id="nameSubmit">
    </form>
    <h1 id="username"></h1><h1>To do list</h1>

<!--        --><?php //if (isset($name)) : ?>
<!--            <h2>Hello --><?//= htmlspecialchars($name); ?><!--!</h2>-->
<!--        --><?php //else: ?>
<!--            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>-->
<!--        --><?php //endif; ?>

        <form action="/addItem" method="post">
            <label for="addTodo">Add a to-do item</label>
            <input type="text" id="addTodo" name="addTodo">
            <input type="submit" id="todoSubmit">
        </form>

        <div id="displayTodo">
            <h2>To do items</h2>
            <?php if(isset($items)) :
                foreach($items as $item) {
                    echo '<li>' . $item["item"] . '<input type="checkbox" value="' . $item["id"] . '" class="itemCheck"></li><br>';
                    }
            ?>
            <?php else: ?>
                <p></p>
            <?php endif; ?>

        </div>
        <div>
            <h2>Done items</h2>
            <div id="doneTodo">

            </div>
        </div>

    <script>
        const nameField = document.getElementById("username");
        const userNameForm = document.getElementById("userNameForm");
        let itemCheckBtnList = document.querySelectorAll(".itemCheck");
        const doneTodo = document.getElementById("doneTodo");

        (function(){
            userNameForm.addEventListener("submit", function(e) {
                e.preventDefault();

                let user = userNameForm.item.value;
                nameField.innerText = user;
                userNameForm.reset();
            })

            for(let i = 0; i < itemCheckBtnList.length; i ++) {
                itemCheckBtnList[i].addEventListener("change", function(e) {
                    let url = '/moveItem'

                    fetch(url, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({taskId : this.value})
                    })
                        .then(response => response.json())
                        .then((obj) => console.log(obj))
                })
            }


        })()
    </script>
    </body>
</html>
